language: go
os: osx
osx_image: xcode10.2
go:
- 1.11
install:
- export GO111MODULE=off
- go get -u github.com/golang/lint/golint
- go get -u github.com/EngoEngine/engo
- go get -u github.com/Noofbiz/tmx
- go get -u github.com/go-gl/mathgl/mgl32
- go get -u github.com/golang/freetype
- go get -u github.com/hajimehoshi/go-mp3
- go get -u github.com/hajimehoshi/oto
- go get -u github.com/jfreymuth/oggvorbis
- go get -u github.com/srwiley/oksvg
- go get -u github.com/srwiley/rasterx
script:
- golint ./...
- go test game.go
notifications:
  webhooks: 
    secure: of5SED+n7UHCTqFcOee0Y/JcHSN2dwzjovve4PN7PilSIHzbfBtN2nAdKu55XdEhdWvP9HLKHlHG8jKd4BVWEh2mNah1qDj0MvenePVbTypyD8I844XUlPi//EYMZgRg5/6eGvtANX+rajHjXJvJdz+4tyE/bJGPFHihKESNWNxEAzNheThEIb7WAMju/v8so43/wprRMspQ/uTrJgxITICl9GqAK01GZisVg2YKkekTncSJFW3U8wj19y0UShzRznufvctOVH4Ce54YWdvS3V4wGi6eHwkKTBhJIE8fpSH+hvuZ5UPMv1zNxHrk0msmJuulSjsUotu946lUACAEsBwt+jDab40BS0ItzooonzmaxkIaIYcUorvC40LeU0sIc2AZOFpnArrGJoudl9HJycyRPhQ/uN4DP2zepGPoFd2G4p4R2H3UkjZS630jD8OScLMrSASNFONZ31c9wTpqKaHmcSu+qeIcOKxrhomI91VpynNZUOys5G5H0k/2coqD/u2daNUaSV1gJ9xl1qHnD/KQwDPSGLUmeNA7xCiheQC6ErIcuIbd+96vJXHfK6/vhyHUgQt1Yf7DIXx5+9b7jwLvVDU0LrbYoewXiUYa8l84+IQqxllUYYTDpsX2oSSRdoYfWZV+vflxDP8mSLxuS/7wG3DYTqybf6aI8Zu5BxE=
